### ISSUE TITLE
show_colors = true not working

### ISSUE THREAD

**Issue by jacobrreed** [AndreM222/copilot-lualine#10]
![image](https://github.com/AndreM222/copilot-lualine/assets/25580051/b2e9dbb9-c588-46b5-bbec-eb9707a13fe2)

```        
lualine_x = {
          { "copilot", show_loading = true, show_colors = true, padding = { right = 1, left = 1 } },
```

![image](https://github.com/AndreM222/copilot-lualine/assets/25580051/159f4d38-638f-4f75-898b-e760d9638870)

![image](https://github.com/AndreM222/copilot-lualine/assets/25580051/e56ddffa-494c-460e-ad16-06a159c37df5)

**Comment by AndreM222** [comment]
It is working but someone just added a new color which is the white one for sleep. You can change it. I will Update the pictures soon.
```
symbols = {
        status = {
            hl = {
                sleep = "#AEB7D0", -> Here
            }
        },
    },

```

**Comment by abhinavnatarajan** [comment]
I believe there is still a small bug that is causing this issue. The following line
https://github.com/AndreM222/copilot-lualine/blob/9e226cf8f4653e13ec282f5878d66aa435899c8c/lua/lualine/components/copilot.lua#L124
should just be `elseif copilot.is_sleep() then` (without the negation).
This makes the plugin work for me:
![Screenshot 2024-06-07 024220](https://github.com/AndreM222/copilot-lualine/assets/25101966/d5509aa0-9a96-4b10-95f1-cbc163b13b16)

**Comment by AndreM222** [comment]
> I believe there is still a small bug that is causing this issue. The following line
> 
> https://github.com/AndreM222/copilot-lualine/blob/9e226cf8f4653e13ec282f5878d66aa435899c8c/lua/lualine/components/copilot.lua#L124
> 
> 
> should just be `elseif copilot.is_sleep() then` (without the negation).
> This makes the plugin work for me:
> ![Screenshot 2024-06-07 024220](https://private-user-images.githubusercontent.com/25101966/337493498-d5509aa0-9a96-4b10-95f1-cbc163b13b16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MjU0MzgsIm5iZiI6MTcxNzcyNTEzOCwicGF0aCI6Ii8yNTEwMTk2Ni8zMzc0OTM0OTgtZDU1MDlhYTAtOWE5Ni00YjEwLTk1ZjEtY2JjMTYzYjEzYjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDAxNTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNjg5YzdkNDdlNTkyN2ViNGVkZjYyMGVjMWUzMTZmNjQyNDhmOThmZTBlYmZkOTc2MGI3MmFlZGJiN2QwZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pZRWXYF-dN7HIP9S3kSHdRyodmLK8fEQpHEeXRypABw)

I made the change in the latest commit.

**Comment by abhinavnatarajan** [comment]
Thanks for the quick fix! 👍

**Comment by Ahsene3** [comment]
Yeah colors are working when I disable copilot suggestions.
