### ISSUE TITLE
Spinner animation speed

### ISSUE THREAD

**Issue by Galicarnax** [AndreM222/copilot-lualine#11]
The timeout between spinner "frames" is too large in my case. Is there a way to control the speed of spinner animation? Looking into the code, cannot see anything obvious. Does that depend on some global nvim's or lualine's config?

**Comment by AndreM222** [comment]
I am unsure of how slow is loading in your end. Something I have in my settings is a update time faster than default that you can set like this

```vim
vim.opt.updatetime = 100
```

**Comment by Galicarnax** [comment]
I've played around with `updatetime`, it does change the behavior, but not in a way I expected. I had no time yet to investigate in more depth, you may close the issue, my feeling is that it's not related to `copilot-lualine`.

**Comment by AndreM222** [comment]
Okay, I hope for the best for you my friend.
