### ISSUE TITLE
Incorrect symbol (fonts issue?)

### ISSUE THREAD

**Issue by Galicarnax** [AndreM222/copilot-lualine#2]
I have `copilot-lualine` plugin installed on two different hosts, with default settings on both. On one host, the symbol in the lualine looks like the one in your screenshots, but on another host I have something like sofa (?) instead:
![screenshot-2024-01-15_13-47-07](https://github.com/AndreM222/copilot-lualine/assets/44889241/a5bd5b03-9512-43d5-99c6-ea6ee76adf77)
So I guess there is some another requirement for your plugin, except the three listed currently?

**Comment by AndreM222** [comment]
Are you using nerd fonts?

**Comment by AndreM222** [comment]
For the icons being used you are required to use this font -> https://www.nerdfonts.com/#home

But you can always switch the icons to your desired ones

**Comment by Galicarnax** [comment]
Ok, so it does matter which nerd font is installed. On my first host with correct icon I have `ttf-firacode-nerd` installed, and on the second host I had `nerd-fonts-noto-sans-mono` installed. After installing `ttf-firacode-nerd` on the second one, I get correct icon. Thank you.

**Comment by AndreM222** [comment]
This shouldnt matter since I also use firacode. try updating it
